name: organizer
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  redux: "^3.0.0"
  flutter_redux: "^0.5.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true