name: organizer
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  redux: "^3.0.0"
  flutter_redux: "^0.5.0"
  redux_logging: "^0.3.0"
  firebase_auth: "^0.5.9"
  cloud_firestore: "^0.7.1"
  google_sign_in: "^3.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true